import i18n from "i18next";
import { initReactI18next } from "react-i18next";

import RenderPressMedia from './RenderPressMedia';

import logo from './logo.svg';
import './App.css';

i18n
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    // the translations
    // (tip move them in a JSON file and import them,
    // or even better, manage them via a UI: https://react.i18next.com/guides/multiple-translation-files#manage-your-translations-with-a-management-gui)
    resources: {
      en: {
        translation: {
          "Welcome to React": "Welcome to React and react-i18next",
          press: {
            text: "files {{media}}",
            media: {
              phone: " by phone",
              letter: "bu letter",
              email: "bu email"
            }
          }
        }
      }
    },
    lng: "en", // if you're using a language detector, do not define the lng option
    fallbackLng: "en",

    interpolation: {
      escapeValue: false // react already safes from xss => https://www.i18next.com/translation-function/interpolation#unescape
    }
  });

function App() {
  const data = [
    {
      id: 65,
      media: 'LETTER',
      firstPlannedDate: '2021-09-03',
      plannedDate: '2021-09-03',
      comment: 'autogenerated',
      createdDate: '2021-08-27T09:43:52',
      lastModifiedDate: '2021-08-27T09:43:52',
    },
  ];
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
      <RenderPressMedia pressPlannedData={data} />
    </div>
  );
}

export default App;
