import { render, screen } from '@testing-library/react';
import RenderPressMedia from './RenderPressMedia';

 const data = [
  {
   id: 65,
   media: 'LETTER',
   firstPlannedDate: '2021-09-03',
   plannedDate: '2021-09-03',
   comment: 'autogenerated',
   createdDate: '2021-08-27T09:43:52',
   lastModifiedDate: '2021-08-27T09:43:52',
  },
 ];

describe('<RenderPressMedia/>', () => {
  it('should display an render press media with data', () => {
    //given
    render(<RenderPressMedia pressPlannedData={data} />);
    //then
    expect(screen.getByText(/letter/i)).toBeInTheDocument();
  });
});
